# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Brenstuhl
email: scott.brenstuhl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Scott Brenstuhl, aspiring data scientist and 
  continuous learner. Check out what I’ve been working on 
  and feel free to reach out! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: scottbrenstuhl
github_username: 808sandbr
linkedin_username: scottbrenstuhl

# Build settings
markdown: kramdown
permalink: /:title
exclude: ["Projects", "808sandbr_depreciated"]